@baseURL = localhost:3333
POST http://{{baseURL}}/applications
content-type: application/json

{
  "name": "João Silva",
  "email": "joao.silva@exemplo.com.br",
  "companyName": "Tech Solutions S.A.",
  "text": "Quero expandir minha rede de contatos e gerar novas oportunidades de negócio na área de TI."
}
###

GET http://{{baseURL}}/admin/applications
###

PUT http://{{baseURL}}/admin/applications/status
content-type: application/json

{
  "id": 10,
  "status": "rejected"
}
###

POST http://{{baseURL}}/members
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao.silva@exemplo.com.br",
  "password": "1234567"
}
###

# @name loginMember
POST http://{{baseURL}}/sessions
content-type: application/json

{
  "email": "joao.silva@exemplo.com.br",
  "password": "1234567"
}
###
@tokenMember = {{loginMember.response.body.token}}
